# Generated by Django 6.0 on 2026-01-04 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='lead',
            name='client_type_detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='client_type_main',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('requirement_yes', 'Requirement Yes'), ('future', 'Future Requirement'), ('reconnect', 'Reconnect'), ('regret', 'Regret Offer')], default='prospect', max_length=30),
        ),
        migrations.CreateModel(
            name='AdditionalContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], max_length=10)),
                ('contact_value', models.CharField(max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_contacts', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_call_date', models.DateField(blank=True, null=True)),
                ('actual_call_date', models.DateField()),
                ('outcome', models.CharField(choices=[('yes', 'Requirement Yes'), ('future', 'Future Requirement'), ('reconnect', 'Reconnect'), ('regret', 'Regret Offer')], max_length=20)),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_history', to='leads.lead')),
            ],
            options={
                'verbose_name_plural': 'Call Histories',
                'ordering': ['-actual_call_date'],
            },
        ),
        migrations.CreateModel(
            name='FutureRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type_main', models.CharField(max_length=50)),
                ('client_type_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('followup_date', models.DateField()),
                ('expected_timeline', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='future_data', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='RegretOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type_main', models.CharField(max_length=50)),
                ('client_type_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('tank_type', models.CharField(max_length=100)),
                ('tank_type_other', models.CharField(blank=True, max_length=100, null=True)),
                ('followup_date', models.DateField()),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regret_data', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementYes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type_main', models.CharField(max_length=50)),
                ('client_type_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('tank_application', models.CharField(max_length=255)),
                ('tank_location', models.CharField(blank=True, max_length=255, null=True)),
                ('tanks_json', models.JSONField(default=list)),
                ('assigned_sales_person', models.CharField(max_length=100)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('sales_stage', models.CharField(choices=[('quotation_sent', 'Quotation Sent'), ('pre_sales', 'Pre-Sales Discussion'), ('meeting_scheduled', 'Meeting Scheduled'), ('waiting_po', 'Waiting for PO'), ('po_received', 'PO Received'), ('order_converted', 'Order Converted'), ('not_converted', 'Not Converted')], default='quotation_sent', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_data', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('quotation_number', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='leads.requirementyes')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateTimeField()),
                ('meeting_type', models.CharField(choices=[('online', 'Online'), ('onsite', 'On-site'), ('phone', 'Phone Call')], default='online', max_length=20)),
                ('attendees', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='leads.requirementyes')),
            ],
            options={
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='StageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(max_length=30)),
                ('to_stage', models.CharField(max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='leads.lead')),
            ],
            options={
                'verbose_name_plural': 'Stage Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
