# Generated by Django 6.0 on 2026-01-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_options_lead_client_type_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirementyes',
            name='current_remark',
            field=models.TextField(blank=True, help_text='Latest update/remark', null=True),
        ),
        migrations.AlterField(
            model_name='requirementyes',
            name='sales_stage',
            field=models.CharField(choices=[('costing_created', 'Costing Created'), ('quotation_created', 'Quotation Created'), ('quotation_sent', 'Quotation Sent to Client'), ('quotation_revision', 'Quotation Under Revision'), ('quotation_accepted', 'Quotation Accepted'), ('po_received', 'PO Received from Client'), ('oa_created', 'OA Created'), ('oa_sent', 'OA Sent to Client'), ('oa_revision', 'OA Under Revision'), ('oa_accepted', 'OA Accepted'), ('order_completed', 'Order Completed'), ('order_lost', 'Order Lost')], default='costing_created', max_length=30),
        ),
    ]
