# Generated by Django 6.0 on 2026-01-05 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_requirementyes_current_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementyes',
            name='assigned_sales_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requirementyes',
            name='current_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirementyes',
            name='lead',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='requirementyes',
            name='sales_stage',
            field=models.CharField(default='quotation_sent', max_length=50),
        ),
        migrations.AlterField(
            model_name='requirementyes',
            name='tank_application',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
