# Generated by Django 6.0 on 2026-01-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_requirementyes_assigned_sales_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_call_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirementyes',
            name='sales_stage',
            field=models.CharField(choices=[('costing_created', 'Costing Created'), ('quotation_created', 'Quotation Created'), ('quotation_sent', 'Quotation Sent'), ('quotation_revision', 'Quotation Revision'), ('quotation_accepted', 'Quotation Accepted'), ('po_received', 'PO Received'), ('oa_created', 'OA Created'), ('oa_sent', 'OA Sent'), ('oa_revision', 'OA Revision'), ('oa_accepted', 'OA Accepted'), ('order_completed', 'Order Completed'), ('order_lost', 'Order Lost')], default='costing_created', max_length=50),
        ),
    ]
